name: Deployment
on:
  push:
    branches: [ CICD ]
  
  workflow_dispatch:
    

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -a
          
      - name: Check out repository code
        uses: actions/checkout@v2
        with: 
          repository: Romain857/MsprJava
          ref: master
      - name: Setup Java
        uses: actions/setup-java@v2
        with: 
          distribution: 'temurin'
          java-version: '17'
          
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Execution
        run:  mvn install clean compile package
      - name: List files in the repository
        working-directory: ./build
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
