name: Deployment
on:
  push:
    branches: [ CICD ]
  
  workflow_dispatch:
    

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
                
      - name: Check out repository code
        uses: actions/checkout@v2
        with: 
          repository: Romain857/MsprJava
          ref: master
      - name: Setup Java
        uses: actions/setup-java@v2
        with: 
          distribution: 'temurin'
          java-version: '17'
          
      - name: List files in the repository
        run: ls
      
      - name: Execution
        run:  mvn install clean compile package
      - name: List built files
        run: | 
          ls
          tar -cvf build.tar -C build . 
          ls
        
      - name: transfer files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: build.tar
          target: deployment
        
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls
      - name: untaring and moving files
        working-directory: deployment
        run: |
          ls
          sudo tar -xvf deployment/build.tar
      
      - run: echo "🍏 This job's status is ${{ job.status }}."
